# Generated by Django 3.1.3 on 2020-11-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
