# Generated by Django 3.1.3 on 2020-11-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
